feat: add option to disable translate individually
koishijs/novelai-bot pull request #123
Opened 2022-11-20 13:18 UTC by MaikoTan

Fixes #122

2022-11-20 16:16 UTC, shigma requested changes

2022-11-20 16:16 UTC, shigma commented on src/index.ts
> +    .option('disable-translate', '-d', { hidden: !!ctx.translator && config.translator })
```suggestion
    .option('noTranslator', '-T', { hidden: () => !ctx.translator || !config.translator })
```

1. 这里逻辑是不是反了？
2. 参数会自动 hyphenate 所以不用担心
3. 使用函数可以支持 hot reload

2022-11-20 16:16 UTC, shigma commented on src/index.ts
> +      if (config.translator && ctx.translator && !options['disable-translate']) {
```suggestion
      if (config.translator && ctx.translator && !options.noTranslator) {
```

2022-11-20 22:37 UTC, MaikoTan commented on src/index.ts
> +    .option('disable-translate', '-d', { hidden: !!ctx.translator && config.translator })
I see. good for it

2022-11-21 01:15 UTC, shigma reviewed
Missing translation for the new option

2022-11-21 01:16 UTC, MaikoTan commented
Oh you're right
Patch is on the way!

2022-11-21 01:32 UTC, shigma commented on src/locales/zh-CN.yml
> +      noTranslator: 在此次调用中禁用翻译
```suggestion
      noTranslator: 禁用自动翻译
```

2022-11-21 01:33 UTC, merged

2022-11-21 01:42 UTC, MaikoTan commented on src/locales/zh-CN.yml
> +      noTranslator: 在此次调用中禁用翻译
Bruh