feat: add iter option for generate multiple images
koishijs/novelai-bot pull request #131
Opened 2022-11-24 02:02 UTC by MaikoTan

with same parameters except seed

close #71 

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/19927330/203677514-d25a4693-f316-4d01-a492-d18cf1b9ecfa.png)

</details>

2022-11-24 15:34 UTC, MaikoTan commented on src/config.ts
> +    maxIteration: Schema.natural().description('允许的最大请求次数 (设置为 1 以禁用同时请求多张图片)。').default(1),
```suggestion
    maxIteration: Schema.natural().description('允许的最大请求次数。').default(1),
```

2022-11-24 16:56 UTC, shigma commented on src/index.ts
> +          return { model, input: prompt, seed: parameters.seed + seedOffset, parameters: omit(parameters, ['prompt', 'seed']) }
原来 seed 在 parameters 里，现在跑到外面了，这是预期的吗？

2022-11-24 23:16 UTC, MaikoTan commented on src/index.ts
> +          return { model, input: prompt, seed: parameters.seed + seedOffset, parameters: omit(parameters, ['prompt', 'seed']) }
oh, I see.

Maybe I am just too tired.

2022-11-24 23:26 UTC, MaikoTan commented on src/config.ts
> +    maxIteration: Schema.natural().description('允许的最大请求次数。').default(1),
```suggestion
    maxIteration: Schema.natural().description('允许的最大绘制次数。').default(1),
```

2022-11-25 01:31 UTC, shigma commented on src/index.ts
> +          parameters.seed = parameters.seed + seedOffset
你每次都累加了……等于是 0 1 3 6 10 15……

2022-11-25 01:33 UTC, MaikoTan commented on src/index.ts
> +          parameters.seed = parameters.seed + seedOffset
......

Watching the World Cup overnight is devil.

2022-11-25 01:36 UTC, shigma commented on src/index.ts
> +          parameters.seed = parameters.seed + seedOffset
你可以 getData 不接受参数，然后改为每次执行前去 +1。

2022-11-25 01:41 UTC, MaikoTan commented on src/index.ts
> +          parameters.seed = parameters.seed + seedOffset
See if this satisfy thee

2022-11-25 01:48 UTC, shigma commented on src/index.ts
> +      for (let offset = 0; offset < iterations; offset++, parameters.seed++) {
所以这里实际上可以用 it-- 了（不过无所谓）

2022-11-25 01:48 UTC, shigma commented on src/index.ts
> +      const genData = () => {
改成 toPayload 或者 getPayload 吧，data 用太多了（之前写 data 是因为直接对象字面量）

2022-11-25 01:49 UTC, MaikoTan commented on src/index.ts
> +      for (let offset = 0; offset < iterations; offset++, parameters.seed++) {
Here not to use `it--` is because we are using `offset` to determine whether we should send the verbose message under the hood.

2022-11-25 01:51 UTC, MaikoTan commented on src/index.ts
> +      const genData = () => {
Sure, I think `getPayload` is better. Thou would use `toPayload` like `toPayload(payloadLikeObject)`.

2022-11-25 01:52 UTC, shigma commented on src/index.ts
> +      for (let offset = 0; offset < iterations; offset++, parameters.seed++) {
但你也可以把下面的 seed 改成 parameters.seed。

2022-11-25 01:54 UTC, MaikoTan commented on src/index.ts
> +      for (let offset = 0; offset < iterations; offset++, parameters.seed++) {
Done.

2022-11-25 01:56 UTC, shigma commented on src/index.ts
> +      for (let offset = 0; offset < iterations; offset++, parameters.seed++) {
那你现在就可以改 offset 了（

2022-11-25 01:59 UTC, shigma requested changes
此外目前的 cleanUp 实现有误。考虑下面的两种改法：

- 将 cleanUp 移至 for 外面完成
- 对 iteration 的情况添加多个 id，然后每次删一个（我个人觉得这样比较合理）

2022-11-25 02:03 UTC, MaikoTan commented on src/index.ts
> +      for (let offset = 0; offset < iterations; offset++, parameters.seed++) {
But then how could I know which iteration is the first one....

2022-11-25 03:01 UTC, MaikoTan commented on src/index.ts
> +      const ids = getRandomId()
I don't really know what is the id using here. See if this satisfy thee.

2022-11-25 03:10 UTC, shigma commented on src/index.ts
> +      const ids = getRandomId()
下面的 for 循环内部没有 try（request 有但是下面的 send 仍然可能报错），导致可能 id 无法回收。

2022-11-25 03:11 UTC, shigma commented on src/index.ts
> +      const ids = getRandomId()
你可能得把循环体再包一层函数，然后 for try 内部调用它

2022-11-25 03:24 UTC, shigma requested changes
建议迷子看球以后好好休息再写代码 🤣

2022-11-25 03:24 UTC, shigma commented on src/index.ts
> +          throw err
这里不能 rethrow 啊不然之后 id 又没法处理了

2022-11-25 03:24 UTC, shigma commented on src/index.ts
> +            return await session.send(handleError(session, err))
这里语义变了，跟下面不一样，还是应该 continue

2022-11-25 03:28 UTC, MaikoTan commented on src/index.ts
> +            return await session.send(handleError(session, err))
I thought here you get the exception other than timeout so you should exit here instead of keeping trying?

2022-11-25 03:29 UTC, MaikoTan commented on src/index.ts
> +          throw err
Oh, should I cache the error after then?

2022-11-25 03:35 UTC, shigma commented on src/index.ts
> +            return await session.send(handleError(session, err))
哦，原来的行为是对的，你第一遍改错了，现在改回去了，是没问题的

2022-11-25 03:36 UTC, shigma commented on src/index.ts
> +          throw err
两种做法，要么你用 AggregateError 之类的东西存一下，要么直接 catch 到错误以后把后续 id 全部 cleanup 了然后 re-throw。要不就直接后一种做法吧。

2022-11-25 03:41 UTC, MaikoTan commented on src/index.ts
> +          throw err
I thought the AggregateError is unknowledgable like a penalty kick, so I choose the second one.

2022-11-25 16:32 UTC, merged