feat: 捕获 JSON 解析失败的情况
koishijs/novelai-bot pull request #220
Opened 2023-12-24 13:43 UTC by idanran

2023-12-25 05:57 UTC, MaikoTan commented
If you are going to catch that error, you MUST handle it rather than leave it blank in the `catch` block.

2023-12-25 07:39 UTC, idanran commented
> If you are going to catch that error, you MUST handle it rather than leave it blank in the `catch` block.

changed

2023-12-25 08:53 UTC, MaikoTan approved these changes

2024-01-09 17:27 UTC, shigma reviewed
你是不是应该处理它，而不是单纯 warn 一下？这里的 res.data.info 是不可解析的吗？

2024-01-09 18:51 UTC, idanran commented
> 你是不是应该处理它，而不是单纯 warn 一下？这里的 res.data.info 是不可解析的吗？

更改了

2024-01-10 01:18 UTC, MaikoTan commented
> `res.data.info` 有两种意外的类型，一个是 undefined，另一个是 object

Then what does `JSON.parse()` do, suppose that it can only be undefined or object?

2024-01-10 03:44 UTC, idanran commented
> > `res.data.info` 有两种意外的类型，一个是 undefined，另一个是 object
> 
> Then what does `JSON.parse()` do, suppose that it can only be undefined or object?

throws an error

2024-02-03 15:25 UTC, shigma requested changes

2024-02-03 15:25 UTC, shigma commented on src/index.ts
> +                if (output !== 'minimal') logger.warn(err)
```suggestion
                logger.warn(err)
```

`output` is not relavent to logger.

2024-02-03 15:26 UTC, merged